name: mamicare_plus2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  firebase_core: ^3.15.1
  firebase_auth: ^5.7.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  provider: ^6.1.1 
  shared_preferences: ^2.2.2
  image_picker: ^1.1.0
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.3
  google_fonts: ^6.0.0
  flutter_local_notifications: 17.2.4
  timezone: ^0.9.2
  permission_handler: ^12.0.1
  font_awesome_flutter: ^10.7.0
  confetti: ^0.7.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/




